name: CI openresty-geoip

on:
  push:
    branches:
      - main
      - ci # TODO: remove
    paths:
      - 'alpine-openresty-geoip/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v5

      - name: Define vars
        id: vars
        shell: bash
        run: |
          # Get commit date in YYYYMMDD format
          COMMIT_DATE=$(git show -s --format=%cd --date=format:%Y%m%d $GITHUB_SHA)

          DOCKER_IMAGE_TAG="${GITHUB_REF_SLUG}-${COMMIT_DATE}-run-${GITHUB_RUN_NUMBER}"

          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
          echo "Docker image tag will be: $DOCKER_IMAGE_TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/alpine-openresty-geoip:${{ env.DOCKER_IMAGE_TAG }}
